name: Build and Publish Image to Docker Hub


on:
  push:
    branches: ["main"]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set image tag
        run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
      - name: Debug secret
        run: echo "TOKEN LENGTH $(echo -n '${{ secrets.DOCKER_HUB_TOKEN_VICTORARJONA }}' | wc -c)"
      - name: build Image
        run: docker build . -t victorarjona10/backend:${{ env.IMAGE_TAG }}
      - name: Login to Docker Hub
        run: docker login -u "victorarjona10" -p "${{ secrets.DOCKER_HUB_TOKEN_VICTORARJONA }}"
      - name: Push image to Docker Hub
        run: docker push victorarjona10/backend:${{ env.IMAGE_TAG }}
