name: Build and Publish Image to Docker Hub

on:
  push:
    branches: ["main"]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set image tag
        run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
      - name: build Image
        run: docker build ../ -t victorarjona10/backend:${{ env.IMAGE_TAG }}
      - name: push image to docker hub
        run: 
          echo "${{ secrets.DOCKER_HUB_TOKEN_VICTORARJONA }}" | docker login -u "victorarjona10" --password-stdin
          docker push victorarjona10/backend:${{ env.IMAGE_TAG }}
